// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0zRVezJAQ0doRaTxKySRB7B2y0rqheHE',
    appId: '1:729314384278:web:6f16e17cb10ba3eda7a5b7',
    messagingSenderId: '729314384278',
    projectId: 'meditasyonnn1',
    authDomain: 'meditasyonnn1.firebaseapp.com',
    storageBucket: 'meditasyonnn1.appspot.com',
    measurementId: 'G-X4MK8SC1DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9sETkgEp8eSadUpB4Lxp8fNG1_AmkG1Q',
    appId: '1:729314384278:android:1011481ab94c6f2ca7a5b7',
    messagingSenderId: '729314384278',
    projectId: 'meditasyonnn1',
    storageBucket: 'meditasyonnn1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCayoSU0njDWGdBFKCqgiF9Vdb8qiVL2m8',
    appId: '1:729314384278:ios:883daa1195c14a49a7a5b7',
    messagingSenderId: '729314384278',
    projectId: 'meditasyonnn1',
    storageBucket: 'meditasyonnn1.appspot.com',
    iosClientId: '729314384278-2ksh18fctci8bnf8gb1o3neqn9f8aoai.apps.googleusercontent.com',
    iosBundleId: 'com.ile.meditasyon.meditasyon',
  );
}
